spring:
  application:
    name: lms-core-streaming
  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}
      password: ${REDIS_PASSWORD}
      timeout: 6000
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    listener:
      simple:
        retry:
          max-attempts: 3
          initial-interval: 20000
          enabled: true
          multiplier: 2

app:
  netty:
    port: 8088
  playback:
    secret: ${STREAMING_SECRET_KEY}
  ffmpeg:
    bin: ${STREAMING_PATH_FFMPEG}
  dir:
    origin-path: ${SERVER_FILE_PATH}
  security:
    hash:
      key: ${SHORT_LINK_HASH_KEY}
  redis:
    key-streaming: "lms:streaming:"
  storage:
    s3:
      endpoint: ${STORAGE_ENDPOINT}
      access-key: ${STORAGE_ACCESS_KEY}
      secret-key: ${STORAGE_SECRET_KEY}
      bucket-staging: ${STORAGE_BUCKET_STAGING}
      bucket-production: ${STORAGE_BUCKET_PRODUCTION}